### PR TITLE
implemented Heading, Description and Video on the Home Page

### PR DESCRIPTION
**Pull request by Nazeeh2000**
@anushbhatia Implemented Basic Description Text of the Home page.

Also added video player on the Home page.
(It plays a dummy video right now. Later on, the source Path of the video would be changed)

Screenshot (50)
Screenshot (49)

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Fix the merge conflict, please

**Comment by Nazeeh2000** [comment]
@anushbhatia Conflicts resolved

**Comment by smaranjitghose** [comment]
Please update with the current Home page

**Comment by anushbhatia** [comment]
Add a relevant social media video and play video without audio and don't use a audio player for this and 
Add headings and text in a proper format

**Comment by Nazeeh2000** [comment]
> Add a relevant social media video and play video without audio and don't use a audio player for this and
> Add headings and text in a proper format

Can you give little more description that how do you want to format the heading?

**Comment by anushbhatia** [comment]
https://www.townscript.com/in/vadodara

**Comment by ashishnagpal2498** [comment]
@Nazeeh2000  .If you don't reply to the conversation and complete in in 3 days. Unfortunately I have to close this PR.

**Pull request closed without merging**
