### PR TITLE
Home page issue#7 Footer 

### PR DESCRIPTION
**Pull request by chetnaSharma24**
Hello

1) I have included the footer in the existing project 
2) I have included the Footer component  and 
   have given the route in App.js file

@anushbhatia kindly check

I am attaching the screenshot here

screencapture-localhost-3000-2020-08-16-19_14_01

### CODE REVIEW

**Comment by smaranjitghose** [comment]
extra_spacing
There is extra spacing

**Comment by chetnaSharma24** [comment]
@smaranjitghose  kindly check now I Have made the changes.

**Comment by chetnaSharma24** [comment]
I have updated the footer 
@smaranjitghose  kindly check

screencapture-localhost-3000-2020-08-17-00_52_58

**Comment by smaranjitghose** [comment]
@chetnaSharma24  Please check this deploy for the same: https://deploy-preview-28--social-scheduler.netlify.app/

**Comment by chetnaSharma24** [comment]
@smaranjitghose  
hey , it is deployed on netllify but i guess one of the label named review changes requested is not removed.

**Comment by chetnaSharma24** [comment]
@smaranjitghose  
and could you please tell how will i get to know that my PR is merged or not

**Comment by anushbhatia** [comment]
yes resolve this conflict i will merge it

**Comment by chetnaSharma24** [comment]
I removed the space @anushbhatia .. is there something else , coould please Little bit elaborate.

**Pull request merged**
