### PR TITLE
dependencies updated

### LINKED ISSUE #20: Update the dependecies to the latest version
Update all the dependencies for the project to the latest version and make sure to correct any breaking changes whatsoever.
Also audit fix any vulnerabilities found while doing so.

### PR DESCRIPTION
**Pull request by sayashchaudhary**
closes #20

### CODE REVIEW

**Comment by abhu-A-J** [comment]
> _No description provided._

Please attach issue number from next time on PR :+1: . #20 

Also can you add the .idea to the gitignore doesn't seem relevant here!

**Comment by sayashchaudhary** [comment]
.idea is folder is added to gitignore

**Comment by anushbhatia** [comment]
Solve the merge conflict

**Comment by sayashchaudhary** [comment]
merge conflict resolved

**Comment by sayashchaudhary** [comment]
Is my branch merged with master ?

**Comment by sayashchaudhary** [comment]
Because on pulling the master, its showing 4999 vulnerabilities

**Pull request merged**
