### PR TITLE
Detail in contact page issue#7

### PR DESCRIPTION
**Pull request by chetnaSharma24**
hello,

1) I have added Detail.js file for the component
2)  I have added the  detail.css for css styling 
and the myinfo.js for the call of component
3) I have added the route "/detail" for the contact page in App.js
4) I have added the bootstrap and images 
5)Attaching the screenshot

kindly check @anushbhatia 

screencapture-localhost-3000-detail-2020-08-15-23_17_24

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@chetnaSharma24 Can you please show me where is the HTML file to load this page? What is the "d" file you have committed? Is it a diff file of the commits so far?

**Comment by chetnaSharma24** [comment]
@smaranjitghose the d file was added my mistake. I have made the changes kindly check now. :)

**Comment by smaranjitghose** [comment]
> @smaranjitghose the d file was added my mistake. I have made the changes kindly check now. :)

Can you please show me the preview of the page here: https://deploy-preview-19--social-scheduler.netlify.app/

**Comment by chetnaSharma24** [comment]
@smaranjitghose  
 could you please little bit elaborate what  actually has to be done in this issue , i am a beginner in this and I think i am not getting your point .
What I have actually done in this is - I have made a route "/detail" , when you type this on the url you will see the page that i have made.  
do I have to include the Detail as one of the navbar links??

**Comment by anushbhatia** [comment]
Routing isn't working please attach the screenshot of the screen

**Comment by Souvikns** [comment]
As there are no /details link in the main site, during production we need to add redirect settings in netlify. 
I found [this](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/#:~:text=The%20most%20common%20strategy%20to%20enable%20redirects%20in,public%2F.%20A%20basic%20redirect%20looks%20something%20like%20this%3A). This might solve the above issue.

**Pull request merged**
